/****************** packages and imports **************/

package com.joseruiz.formMaker.compiler;

import java_cup.runtime.*;
import java.util.*;

/*------------------------------------------------------
                        CUP
--------------------------------------------------------*/
parser code {:

    Lexer lex;
    private List<ErrorReport> errorList;

    // conexion de parser y lexer
    public Parser(Lexer lex){
        super(lex);
        errorList = new ArrayList<>();
    }

    // getters

    public List<ErrorReport> getSyntaxErrors(){
        return this.errorList;
    }

    private void customError(Symbol cur_token){
        StringBuilder lexema = new StringBuilder();
        if (cur_token.value != null) {
            lexema.append(cur_token.value.toString());
        } else {
            lexema.append(symbl_name_from_id(cur_token.sym));
        }

        StringBuilder descripcionError = new StringBuilder();

        if( expected_token_ids().isEmpty() ){
            descripcionError.append("Ya no se esperaba ningun simbolo");
        } else {
            descripcionError.append(" Se esperaba: ");
            for(Integer expected_token_id : expected_token_ids() ){
                descripcionError.append(symbl_name_from_id(expected_token_id));
                descripcionError.append(" ");
            }
        }

        errorList.add(new ErrorReport(lexema.toString(), cur_token.left, cur_token.right, "Sintactico", descripcionError.toString()));
    }

    // metodos de error
    public void syntax_error(Symbol cur_token){
        customError(cur_token);
    }

    public void unrecovered_syntax_error(Symbol cur_token){
        StringBuilder lexema = new StringBuilder();
        if (cur_token.value != null) {
            lexema.append(cur_token.value.toString());
        } else {
            lexema.append(symbl_name_from_id(cur_token.sym));
        }
        errorList.add(new ErrorReport(lexema.toString(), cur_token.left, cur_token.right, "Sintactico", "Error que no se puede recuperar"));
    }

:}

/*----------------------------------------------------------
                         reglas
-----------------------------------------------------------*/

/* Terminales: tokens que el parser nos retorna */
terminal     PLUS, MINUS, TIMES, DIVIDE, POWER, MOD, LPAREN,RPAREN,
             GT, LT, GTE, LTE, EQ, NEQ,
             AND, OR, NOT,
             TYPENUMBER, TYPESTRING, TYPESPECIAL,
             ASSIGN,
             LBRACE, RBRACE, LBRACKET, RBRACKET, COLON, SEMICOLON, COMMA, DOT, COMODIN,
             SECTION, WIDTH, HEIGHT, LABEL, OPTIONS, CONTENT, POINTX, POINTY, ORIENTATION,
              VERTICAL, HORIZONTAL, ELEMENTS, STYLES, TABLE, TEXT,
              OPEN_QUESTION, DROP_QUESTION, CORRECT, SELECT_QUESTION, MULTIPLE_QUESTION, DRAW,
              IF, ELSE, WHILE, DO, FOR, IN, RANGE,
              RED, BLUE, GREEN, PURPLE, SKY, YELLOW, BLACK, WHITE,
              HEX_COLOR, RGB_COLOR, HSL_COLOR,
              NUMBER,
              PARAMCOLOR, PARAMBACKGROUND, PARAMFONT, PARAMSIZE, PARAMBORDER,
              MONO, CURSIVE, SANS_SERIF,
              LINE, DOTTED, DOUBLE,
              ID, STRCHAIN,
              POKEAPI, APINUMBER
            ;

// TODO: agregar lo demás
/* no terminales, reglas que nosotros vamos a definir sintacticamente */
non terminal codigo,
iniciarInt, iniciarString, iniciarSpecial, reasignarInt, reasignarString, reasignarSpecial,
ifStatement, elseStatement, whileStatement, doWhileStatement, forStatement, expression,
section, secPropertiesList, secProperty, secStylesList, secStyle, secElementsList,
UIelementsList, UIelement, text, textPropertiesList, textProperty, textStylesList, textStyle,
question, questionPropertiesList, questionProperty, questionStylesList, questionStyle,
table, tablePropertiesList, tableProperty, tableStylesList, tableStyle, tableElementsList, tableElement, tableElementComponents,
secStylesOrNo, spVerticalHorizontal, textStylesOrNo, questionStylesOrNo, renderQuestion, paramsRenderList, paramRender,
optionsThing, optionsThing2, option, apiPokemonSyntax, apiPokParamList, apiPokParam,
correctOrNo, correctList, correctElement, tableElement2, tableAllowedElements,
tableStylesOrNo, borderStyle, typeBorder, textValue, labelValue,
instruccion, expression2, comparison, math, term1, term2, term3,
codigoSimple, codigoSimple2, tableLine,
color, font, questionOptionalParams, questionOptional
;




/* Gramatica: reglas para validacion */

start with codigo;

codigo ::= codigo instruccion
        | // Sin instrucciones
        ;

 instruccion ::= iniciarInt
                | iniciarString
                | iniciarSpecial
                | reasignarInt
                | reasignarString
                | reasignarSpecial
                | ifStatement
                | whileStatement
                | doWhileStatement
                | forStatement
                | section
                | table
                ;

iniciarInt ::= TYPENUMBER ID
            | TYPENUMBER ID ASSIGN math
            ;

iniciarString ::= TYPESTRING ID
            | TYPESTRING ID ASSIGN STRCHAIN
            | TYPESTRING ID ASSIGN ID
            ;

iniciarSpecial ::= TYPESPECIAL ID ASSIGN question;

reasignarInt ::= ID ASSIGN math
            ;

reasignarString ::= ID ASSIGN STRCHAIN
            ;

reasignarSpecial ::= ID ASSIGN question
            ;

ifStatement ::= IF LPAREN expression RPAREN LBRACE codigoSimple RBRACE elseStatement
            ;

elseStatement ::= ELSE IF LPAREN expression RPAREN LBRACE codigoSimple RBRACE elseStatement
            | ELSE LBRACE codigoSimple RBRACE
            |
            ;

whileStatement ::= WHILE LPAREN expression RPAREN LBRACE codigoSimple RBRACE
                ;

doWhileStatement ::= DO LBRACE codigoSimple RBRACE WHILE LPAREN expression RPAREN
                ;

forStatement ::= FOR LPAREN reasignarInt SEMICOLON expression SEMICOLON reasignarInt RPAREN LBRACE codigoSimple RBRACE
                | FOR LPAREN ID IN NUMBER RANGE NUMBER RPAREN LBRACE codigoSimple RBRACE
                ;

expression ::= expression OR expression2
            | expression AND expression2
            | expression2
            ;

expression2 ::= NOT expression2
            | comparison
            ;

comparison ::= math GT math
            | math LT math
            | math GTE math
            | math LTE math
            | math EQ math
            | math NEQ math
            | math
            ;

math ::= math PLUS term1
        | math MINUS term1
        | term1
        ;

term1 ::= term1 TIMES term2
        | term1 DIVIDE term2
        | term2
        ;

term2 ::= term2 POWER term3
        | term2 MOD term3
        | term3
        ;

term3 ::= LPAREN expression RPAREN
        | NUMBER
        | ID
        | COMODIN
        | MINUS term3
        ;

codigoSimple ::= codigoSimple codigoSimple2
                | // Sin instrucciones
                ;

codigoSimple2 ::= iniciarInt
                | iniciarString
                | iniciarSpecial
                | reasignarInt
                | reasignarString
                | reasignarSpecial
                | ifStatement
                | whileStatement
                | doWhileStatement
                | forStatement
                ;

section ::= SECTION LBRACKET secPropertiesList COMMA ELEMENTS COLON LBRACE secElementsList RBRACE secStylesOrNo RBRACKET
            ;

secStylesOrNo ::= COMMA STYLES LBRACKET secStylesList RBRACKET
            |
            ;

secStylesList ::= secStylesList COMMA secStyle
                    | secStyle
                    ;

secStyle ::= PARAMCOLOR COLON color
            | PARAMBACKGROUND COLON color
            | PARAMFONT COLON font
            | PARAMSIZE COLON NUMBER
            | PARAMBORDER COLON borderStyle
            ;

secPropertiesList ::= secPropertiesList COMMA secProperty
                    | secProperty
                    ;

secProperty ::= WIDTH COLON math
                | HEIGHT COLON math
                | POINTX COLON math
                | POINTY COLON math
                | ORIENTATION COLON spVerticalHorizontal
                ;

spVerticalHorizontal ::= VERTICAL
                        | HORIZONTAL
                        ;

secElementsList ::= UIelementsList
                    ;

UIelementsList ::= UIelementsList COMMA UIelement
                    | UIelement
                    ;

UIelement ::= section
            | table
            | text
            | renderQuestion
            ;

text ::= TEXT LBRACKET textPropertiesList textStylesOrNo RBRACKET
        ;

textPropertiesList ::= textPropertiesList COMMA textProperty
                    | textProperty
                    ;

textProperty ::= WIDTH COLON math
                | HEIGHT COLON math
                | CONTENT COLON textValue
                ;

textValue ::= STRCHAIN
            | ID
            ;

textStylesOrNo ::= COMMA STYLES LBRACKET textStylesList RBRACKET
                    |
                    ;

textStylesList ::= textStylesList COMMA textStyle
                    | textStyle
                    ;

textStyle ::= PARAMCOLOR COLON color
            | PARAMBACKGROUND COLON color
            | PARAMFONT COLON font
            | PARAMSIZE COLON NUMBER
            ;

color ::= HEX_COLOR
        | RGB_COLOR
        | HSL_COLOR
        | RED
        | BLUE
        | GREEN
        | PURPLE
        | SKY
        | YELLOW
        | BLACK
        | WHITE
        ;

font ::= MONO
        | CURSIVE
        | SANS_SERIF
        ;

renderQuestion ::= ID DOT DRAW LPAREN paramsRenderList RPAREN
                ;

paramsRenderList ::= paramsRenderList COMMA paramRender
                | paramRender
                | // Sin params
                ;

paramRender ::= STRCHAIN
                | math
                ;

question ::= OPEN_QUESTION LBRACKET questionPropertiesList questionStylesOrNo RBRACKET
            | DROP_QUESTION LBRACKET questionPropertiesList COMMA OPTIONS COLON optionsThing questionOptionalParams RBRACKET
            | SELECT_QUESTION LBRACKET questionPropertiesList COMMA OPTIONS COLON optionsThing questionOptionalParams RBRACKET
            | MULTIPLE_QUESTION LBRACKET questionPropertiesList COMMA OPTIONS COLON optionsThing questionOptionalParams RBRACKET
            ;

questionPropertiesList ::= questionPropertiesList COMMA questionProperty
                    | questionProperty
                    ;

questionProperty ::= WIDTH COLON math
                | HEIGHT COLON math
                | LABEL COLON labelValue
                ;

labelValue ::= STRCHAIN
            | ID
            | COMODIN
            ;

questionStylesOrNo ::= COMMA STYLES LBRACKET questionStylesList RBRACKET
                    |
                    ;

questionStylesList ::= questionStylesList COMMA questionStyle
                    | questionStyle
                    ;

questionStyle ::= PARAMCOLOR COLON color
            | PARAMBACKGROUND COLON color
            | PARAMFONT COLON font
            | PARAMSIZE COLON NUMBER
            ;

optionsThing ::= LBRACE optionsThing2 RBRACE
                | apiPokemonSyntax
                ;

optionsThing2 ::= optionsThing2 COMMA option
                | option
                ;

option ::= STRCHAIN
        ;

apiPokemonSyntax ::= POKEAPI LPAREN apiPokParamList RPAREN
        ;

apiPokParamList ::= apiPokParamList COMMA apiPokParam
                    | apiPokParam
                    ;

apiPokParam ::= APINUMBER
                |NUMBER
                ;

correctOrNo ::= LBRACE correctList RBRACE
                | math
                ;

correctList ::= correctList COMMA correctElement
                | correctElement
                ;

correctElement ::= math
                ;

questionOptionalParams ::= COMMA questionOptional
                        |
                        ;

questionOptional ::= CORRECT COLON correctOrNo questionStylesOrNo
                    | STYLES LBRACKET questionStylesList RBRACKET
                    ;


table::= TABLE LBRACKET tablePropertiesList COMMA tableElementsList tableStylesOrNo RBRACKET
        ;

tablePropertiesList ::= tablePropertiesList COMMA tableProperty
                    | tableProperty
                    ;

tableProperty ::= WIDTH COLON math
                | HEIGHT COLON math
                | POINTX COLON math
                | POINTY COLON math
                ;

tableElementsList ::= ELEMENTS COLON LBRACE tableElementComponents RBRACE
                    ;

tableElementComponents ::= tableElementComponents COMMA tableLine
                    | tableLine
                    ;

tableLine ::=  LBRACKET tableElement RBRACKET
            ;

tableElement ::= tableElement COMMA tableElement2
            | tableElement2
            ;

tableElement2 ::= LBRACE tableAllowedElements RBRACE
                ;

tableAllowedElements ::= UIelement; // Solo un elemento por celda

tableStylesOrNo ::= COMMA STYLES LBRACKET tableStylesList RBRACKET
                    |
                    ;

tableStylesList ::= tableStylesList COMMA tableStyle
                    | tableStyle
                    ;

tableStyle ::= PARAMCOLOR COLON color
            | PARAMBACKGROUND COLON color
            | PARAMFONT COLON font
            | PARAMSIZE COLON NUMBER
            | PARAMBORDER COLON borderStyle
            ;

borderStyle ::= LPAREN NUMBER COMMA typeBorder COMMA color RPAREN
            ;

typeBorder ::= LINE | DOTTED | DOUBLE;