// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: S:/Documents/_UNIProjectsSTASHED/Compiladores1/Compi1Proyecto1/srcTools/lexer.flex

/********************** paquetes y otros ***********************/
package com.joseruiz.formMaker.compiler;

import java_cup.runtime.*;
import java.util.*;


@SuppressWarnings("fallthrough")
public class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\1\1\4\22\0\1\1"+
    "\1\5\1\6\1\7\1\10\1\11\1\12\1\0\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\31\3\32\1\33"+
    "\1\34\1\35\1\36\1\37\1\40\1\41\1\42\1\43"+
    "\1\44\1\45\1\46\1\47\1\50\1\51\1\52\1\53"+
    "\1\54\1\55\1\56\1\57\1\60\1\61\1\62\1\63"+
    "\1\64\1\65\1\66\1\67\1\70\1\71\1\72\1\73"+
    "\1\74\1\75\1\76\1\77\1\100\1\0\1\101\1\102"+
    "\1\103\1\104\1\105\1\106\1\107\1\110\1\111\1\53"+
    "\1\112\1\113\1\114\1\115\1\116\1\117\1\53\1\120"+
    "\1\121\1\122\1\123\1\53\1\124\1\125\1\126\1\127"+
    "\1\130\1\131\1\132\1\133\6\0\1\3\u01a2\0\2\3"+
    "\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\1\1\3\1\1\1\4\1\5"+
    "\1\1\1\6\1\7\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\24\25\1\26\1\27\1\30\13\25\1\31\1\1\1\32"+
    "\1\33\1\34\1\35\1\34\1\36\1\37\5\0\1\40"+
    "\13\0\1\41\1\42\1\43\2\25\1\44\5\25\1\45"+
    "\23\25\1\46\11\25\1\47\1\34\1\50\1\51\1\52"+
    "\1\53\10\0\1\54\2\0\1\16\2\0\7\25\1\55"+
    "\10\25\1\56\3\25\1\57\24\25\2\34\13\0\1\4"+
    "\3\0\1\25\1\60\4\25\1\61\2\25\1\62\1\63"+
    "\10\25\1\64\6\25\1\65\14\25\10\34\12\0\1\66"+
    "\4\25\1\67\10\25\1\70\1\25\1\71\1\72\5\25"+
    "\1\73\10\25\1\74\1\75\1\76\7\34\1\77\1\100"+
    "\15\0\1\25\1\101\1\102\3\25\1\103\1\25\1\104"+
    "\4\25\1\105\3\25\1\106\1\107\2\25\1\110\1\111"+
    "\1\25\1\112\1\113\1\25\6\34\2\0\1\114\2\0"+
    "\1\115\1\116\1\0\1\117\1\0\1\120\5\25\1\121"+
    "\2\25\1\122\1\123\1\25\1\124\1\25\1\125\1\25"+
    "\1\126\5\34\1\0\1\127\2\0\6\25\1\130\1\131"+
    "\2\25\5\34\3\0\10\25\4\34\1\132\2\0\1\133"+
    "\1\25\1\134\2\25\1\135\3\25\2\34\2\0\4\25"+
    "\1\136\1\25\1\34\1\137\1\0\1\140\5\25\1\0"+
    "\1\141\1\25\1\142\2\25\1\0\3\25\1\0\1\25"+
    "\1\143\1\25\1\0\2\25\1\144\1\145\2\25\1\146";

  private static int [] zzUnpackAction() {
    int [] result = new int[471];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\134\0\270\0\270\0\u0114\0\u0170\0\u01cc\0\u0228"+
    "\0\u0284\0\270\0\u02e0\0\u033c\0\270\0\270\0\270\0\270"+
    "\0\270\0\u0398\0\u03f4\0\u0450\0\270\0\270\0\u04ac\0\u0508"+
    "\0\u0564\0\270\0\u05c0\0\u061c\0\u0678\0\u06d4\0\u0730\0\u078c"+
    "\0\u07e8\0\u0844\0\u08a0\0\u08fc\0\u0958\0\u09b4\0\u0a10\0\u0a6c"+
    "\0\u0ac8\0\u0b24\0\u0b80\0\u0bdc\0\u0c38\0\u0c94\0\270\0\270"+
    "\0\270\0\u0cf0\0\u0d4c\0\u0da8\0\u0e04\0\u0e60\0\u0ebc\0\u0f18"+
    "\0\u0f74\0\u0fd0\0\u102c\0\u1088\0\270\0\u10e4\0\270\0\270"+
    "\0\u1140\0\270\0\u119c\0\u11f8\0\270\0\u1254\0\u12b0\0\u130c"+
    "\0\u1368\0\u13c4\0\270\0\u1420\0\u147c\0\u14d8\0\u1534\0\u1590"+
    "\0\u15ec\0\u1648\0\u16a4\0\u1700\0\u175c\0\u17b8\0\270\0\270"+
    "\0\270\0\u1814\0\u1870\0\u18cc\0\u1928\0\u1984\0\u19e0\0\u1a3c"+
    "\0\u1a98\0\u05c0\0\u1af4\0\u1b50\0\u1bac\0\u1c08\0\u1c64\0\u1cc0"+
    "\0\u1d1c\0\u1d78\0\u1dd4\0\u1e30\0\u1e8c\0\u1ee8\0\u1f44\0\u1fa0"+
    "\0\u1ffc\0\u2058\0\u20b4\0\u2110\0\u216c\0\u05c0\0\u21c8\0\u2224"+
    "\0\u2280\0\u22dc\0\u2338\0\u2394\0\u23f0\0\u244c\0\u24a8\0\270"+
    "\0\u2504\0\270\0\270\0\270\0\270\0\u2560\0\u25bc\0\u2618"+
    "\0\u2674\0\u26d0\0\u272c\0\u2788\0\u27e4\0\270\0\u2840\0\u289c"+
    "\0\u1648\0\u28f8\0\u2954\0\u29b0\0\u2a0c\0\u2a68\0\u2ac4\0\u2b20"+
    "\0\u2b7c\0\u2bd8\0\u05c0\0\u2c34\0\u2c90\0\u2cec\0\u2d48\0\u2da4"+
    "\0\u2e00\0\u2e5c\0\u2eb8\0\u05c0\0\u2f14\0\u2f70\0\u2fcc\0\u05c0"+
    "\0\u3028\0\u3084\0\u30e0\0\u313c\0\u3198\0\u31f4\0\u3250\0\u32ac"+
    "\0\u3308\0\u3364\0\u33c0\0\u341c\0\u3478\0\u34d4\0\u3530\0\u358c"+
    "\0\u35e8\0\u3644\0\u36a0\0\u36fc\0\u3758\0\u37b4\0\u3810\0\u386c"+
    "\0\u38c8\0\u3924\0\u3980\0\u39dc\0\u3a38\0\u3a94\0\u3af0\0\u3b4c"+
    "\0\u3ba8\0\270\0\u3c04\0\u3c60\0\u3cbc\0\u3d18\0\u05c0\0\u3d74"+
    "\0\u3dd0\0\u3e2c\0\u3e88\0\u05c0\0\u3ee4\0\u3f40\0\u05c0\0\u05c0"+
    "\0\u3f9c\0\u3ff8\0\u4054\0\u40b0\0\u410c\0\u4168\0\u41c4\0\u4220"+
    "\0\u05c0\0\u427c\0\u42d8\0\u4334\0\u4390\0\u43ec\0\u4448\0\u05c0"+
    "\0\u44a4\0\u4500\0\u455c\0\u45b8\0\u4614\0\u4670\0\u46cc\0\u4728"+
    "\0\u4784\0\u47e0\0\u483c\0\u4898\0\u48f4\0\u4950\0\u49ac\0\u4a08"+
    "\0\u4a64\0\u4ac0\0\u4b1c\0\u4b78\0\u4bd4\0\u4c30\0\u4c8c\0\u4ce8"+
    "\0\u4d44\0\u4da0\0\u4dfc\0\u4e58\0\u4eb4\0\u4f10\0\u05c0\0\u4f6c"+
    "\0\u4fc8\0\u5024\0\u5080\0\u05c0\0\u50dc\0\u5138\0\u5194\0\u51f0"+
    "\0\u524c\0\u52a8\0\u5304\0\u5360\0\u05c0\0\u53bc\0\u05c0\0\u05c0"+
    "\0\u5418\0\u5474\0\u54d0\0\u552c\0\u5588\0\u05c0\0\u55e4\0\u5640"+
    "\0\u569c\0\u56f8\0\u5754\0\u57b0\0\u580c\0\u5868\0\u05c0\0\u1140"+
    "\0\u1140\0\u58c4\0\u5920\0\u597c\0\u59d8\0\u5a34\0\u5a90\0\u5aec"+
    "\0\u1140\0\u1140\0\u5b48\0\u5ba4\0\u5c00\0\u5c5c\0\u5cb8\0\u5d14"+
    "\0\u5d70\0\u5dcc\0\u5e28\0\u5e84\0\u5ee0\0\u5f3c\0\u5f98\0\u5ff4"+
    "\0\u05c0\0\u05c0\0\u6050\0\u60ac\0\u6108\0\u05c0\0\u6164\0\u05c0"+
    "\0\u61c0\0\u621c\0\u6278\0\u62d4\0\u05c0\0\u6330\0\u638c\0\u63e8"+
    "\0\u05c0\0\u05c0\0\u6444\0\u64a0\0\u05c0\0\u05c0\0\u64fc\0\u05c0"+
    "\0\u05c0\0\u6558\0\u65b4\0\u6610\0\u666c\0\u66c8\0\u6724\0\u6780"+
    "\0\u67dc\0\u6838\0\270\0\u6894\0\u68f0\0\270\0\270\0\u694c"+
    "\0\270\0\u69a8\0\u05c0\0\u6a04\0\u6a60\0\u6abc\0\u6b18\0\u6b74"+
    "\0\u05c0\0\u6bd0\0\u6c2c\0\u05c0\0\u05c0\0\u6c88\0\u05c0\0\u6ce4"+
    "\0\u05c0\0\u6d40\0\u1140\0\u6d9c\0\u6df8\0\u6e54\0\u6eb0\0\u6f0c"+
    "\0\u6f68\0\270\0\u6fc4\0\u7020\0\u707c\0\u70d8\0\u7134\0\u7190"+
    "\0\u71ec\0\u7248\0\u05c0\0\u05c0\0\u72a4\0\u7300\0\u735c\0\u73b8"+
    "\0\u7414\0\u7470\0\u74cc\0\u7528\0\u7584\0\u75e0\0\u763c\0\u7698"+
    "\0\u76f4\0\u7750\0\u77ac\0\u7808\0\u7864\0\u78c0\0\u791c\0\u7978"+
    "\0\u79d4\0\u7a30\0\u1140\0\u7a8c\0\u7ae8\0\270\0\u7b44\0\u05c0"+
    "\0\u7ba0\0\u7bfc\0\u05c0\0\u7c58\0\u7cb4\0\u7d10\0\u7d6c\0\u7dc8"+
    "\0\u7e24\0\u7e80\0\u7edc\0\u7f38\0\u7f94\0\u7ff0\0\u05c0\0\u804c"+
    "\0\u80a8\0\u1140\0\u8104\0\270\0\u8160\0\u81bc\0\u8218\0\u8274"+
    "\0\u82d0\0\u832c\0\u05c0\0\u8388\0\u05c0\0\u83e4\0\u8440\0\u849c"+
    "\0\u84f8\0\u8554\0\u85b0\0\u860c\0\u8668\0\u05c0\0\u86c4\0\u8720"+
    "\0\u877c\0\u87d8\0\270\0\u05c0\0\u8834\0\u8890\0\u05c0";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[471];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\2\4\1\0\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\10\24\1\25\1\26\1\27\1\30\1\31"+
    "\1\32\1\3\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\2\33\1\44\1\45\1\46\1\47"+
    "\1\50\1\33\1\51\1\52\1\53\1\33\1\54\1\55"+
    "\1\33\1\56\1\33\1\57\1\3\1\60\1\61\3\33"+
    "\1\62\1\63\1\64\2\33\1\65\1\66\1\33\1\67"+
    "\1\33\1\70\1\71\1\72\1\33\1\73\2\33\1\74"+
    "\3\33\1\75\1\76\1\77\1\100\2\101\1\0\1\101"+
    "\1\0\1\101\1\102\32\101\1\103\33\101\1\104\36\101"+
    "\136\0\1\4\136\0\1\105\230\0\1\106\1\107\2\0"+
    "\1\110\13\0\1\111\34\0\10\112\7\0\6\112\31\0"+
    "\6\112\25\0\2\11\1\0\1\11\1\0\127\11\12\0"+
    "\1\113\144\0\1\114\1\115\1\116\5\117\122\0\1\120"+
    "\127\0\1\121\137\0\1\122\1\0\10\24\124\0\1\123"+
    "\2\124\1\125\4\126\3\0\1\127\133\0\1\130\133\0"+
    "\1\131\120\0\10\33\7\0\32\33\4\0\30\33\27\0"+
    "\10\33\7\0\13\33\1\132\16\33\4\0\30\33\27\0"+
    "\10\33\7\0\24\33\1\133\5\33\4\0\30\33\27\0"+
    "\10\33\7\0\16\33\1\134\2\33\1\135\10\33\4\0"+
    "\30\33\27\0\10\33\7\0\13\33\1\136\16\33\4\0"+
    "\30\33\27\0\10\33\7\0\16\33\1\137\13\33\4\0"+
    "\30\33\27\0\10\33\7\0\21\33\1\140\10\33\4\0"+
    "\30\33\27\0\10\33\7\0\16\33\1\141\13\33\4\0"+
    "\30\33\27\0\10\33\7\0\5\33\1\142\24\33\4\0"+
    "\30\33\27\0\10\33\7\0\10\33\1\143\21\33\4\0"+
    "\30\33\27\0\10\33\7\0\16\33\1\144\5\33\1\145"+
    "\5\33\4\0\30\33\27\0\10\33\7\0\24\33\1\146"+
    "\5\33\4\0\30\33\27\0\10\33\7\0\17\33\1\147"+
    "\12\33\4\0\30\33\27\0\10\33\7\0\24\33\1\150"+
    "\5\33\4\0\30\33\27\0\10\33\7\0\4\33\1\151"+
    "\25\33\4\0\30\33\27\0\10\33\7\0\1\152\3\33"+
    "\1\153\5\33\1\154\17\33\4\0\30\33\27\0\10\33"+
    "\7\0\1\155\3\33\1\156\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\157\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\7\33\1\160\22\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\161\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\32\33\4\0\16\33\1\162\11\33\27\0"+
    "\10\33\7\0\32\33\4\0\20\33\1\163\7\33\27\0"+
    "\10\33\7\0\32\33\4\0\13\33\1\164\14\33\27\0"+
    "\10\33\7\0\32\33\4\0\5\33\1\165\22\33\27\0"+
    "\10\33\7\0\32\33\4\0\15\33\1\166\12\33\27\0"+
    "\10\33\7\0\32\33\4\0\1\33\1\167\26\33\27\0"+
    "\10\33\7\0\32\33\4\0\23\33\1\170\4\33\27\0"+
    "\10\33\7\0\32\33\4\0\17\33\1\171\1\172\7\33"+
    "\27\0\10\33\7\0\32\33\4\0\16\33\1\173\11\33"+
    "\27\0\10\33\7\0\32\33\4\0\17\33\1\174\2\33"+
    "\1\175\5\33\27\0\10\33\7\0\32\33\4\0\10\33"+
    "\1\176\1\177\16\33\135\0\1\200\2\0\2\101\1\0"+
    "\1\101\1\0\1\101\1\0\66\101\1\0\40\101\1\0"+
    "\1\101\1\0\1\101\1\0\65\101\1\201\1\0\36\101"+
    "\6\0\1\202\106\0\1\203\2\0\1\204\1\0\1\205"+
    "\112\0\1\206\14\0\1\207\133\0\1\210\133\0\1\211"+
    "\122\0\1\212\51\0\10\213\7\0\6\213\31\0\6\213"+
    "\44\0\1\214\133\0\1\214\3\0\10\117\120\0\1\214"+
    "\3\0\5\117\1\215\2\114\120\0\1\214\3\0\10\114"+
    "\122\0\1\216\112\0\15\217\1\220\116\217\23\0\10\221"+
    "\120\0\1\222\133\0\1\222\3\0\10\126\120\0\1\222"+
    "\3\0\6\126\1\223\1\123\120\0\1\222\3\0\10\123"+
    "\124\0\10\33\7\0\1\224\23\33\1\225\5\33\4\0"+
    "\30\33\27\0\10\33\7\0\21\33\1\226\10\33\4\0"+
    "\30\33\27\0\10\33\7\0\23\33\1\227\1\230\5\33"+
    "\4\0\30\33\27\0\10\33\7\0\16\33\1\231\13\33"+
    "\4\0\30\33\27\0\10\33\7\0\22\33\1\232\7\33"+
    "\4\0\30\33\27\0\10\33\7\0\21\33\1\233\10\33"+
    "\4\0\30\33\27\0\10\33\7\0\4\33\1\234\25\33"+
    "\4\0\30\33\27\0\10\33\7\0\21\33\1\235\10\33"+
    "\4\0\30\33\27\0\10\33\7\0\15\33\1\236\14\33"+
    "\4\0\30\33\27\0\10\33\7\0\15\33\1\237\14\33"+
    "\4\0\30\33\27\0\10\33\7\0\13\33\1\240\16\33"+
    "\4\0\30\33\27\0\10\33\7\0\14\33\1\241\15\33"+
    "\4\0\30\33\27\0\10\33\7\0\4\33\1\242\25\33"+
    "\4\0\30\33\27\0\10\33\7\0\21\33\1\243\10\33"+
    "\4\0\30\33\27\0\10\33\7\0\3\33\1\244\26\33"+
    "\4\0\30\33\27\0\10\33\7\0\15\33\1\245\14\33"+
    "\4\0\30\33\27\0\10\33\7\0\2\33\1\246\10\33"+
    "\1\247\16\33\4\0\30\33\27\0\10\33\7\0\30\33"+
    "\1\250\1\33\4\0\30\33\27\0\10\33\7\0\1\33"+
    "\1\251\30\33\4\0\30\33\27\0\10\33\7\0\27\33"+
    "\1\252\2\33\4\0\30\33\27\0\10\33\7\0\21\33"+
    "\1\253\10\33\4\0\30\33\27\0\10\33\7\0\10\33"+
    "\1\254\21\33\4\0\30\33\27\0\10\33\7\0\13\33"+
    "\1\255\16\33\4\0\30\33\27\0\10\33\7\0\32\33"+
    "\4\0\15\33\1\256\2\33\1\257\7\33\27\0\10\33"+
    "\7\0\32\33\4\0\1\33\1\260\26\33\27\0\10\33"+
    "\7\0\32\33\4\0\5\33\1\261\22\33\27\0\10\33"+
    "\7\0\32\33\4\0\11\33\1\262\16\33\27\0\10\33"+
    "\7\0\32\33\4\0\2\33\1\263\25\33\27\0\10\33"+
    "\7\0\32\33\4\0\14\33\1\264\13\33\27\0\10\33"+
    "\7\0\32\33\4\0\22\33\1\265\5\33\27\0\10\33"+
    "\7\0\32\33\4\0\11\33\1\266\16\33\27\0\10\33"+
    "\7\0\32\33\4\0\11\33\1\267\16\33\27\0\10\33"+
    "\7\0\32\33\4\0\5\33\1\270\22\33\27\0\10\33"+
    "\7\0\32\33\4\0\20\33\1\271\5\33\1\272\1\33"+
    "\27\0\10\33\7\0\32\33\4\0\16\33\1\273\11\33"+
    "\27\0\10\33\7\0\32\33\4\0\4\33\1\274\23\33"+
    "\4\0\2\101\1\0\1\101\1\0\1\101\1\0\24\101"+
    "\1\275\1\101\1\276\37\101\1\0\36\101\103\0\1\277"+
    "\150\0\1\300\126\0\1\301\135\0\1\302\143\0\1\303"+
    "\31\0\10\304\7\0\6\304\31\0\6\304\50\0\1\305"+
    "\1\306\1\307\5\310\120\0\1\214\3\0\6\114\103\0"+
    "\15\217\1\311\116\217\15\0\1\220\4\0\1\312\134\0"+
    "\1\313\1\314\6\315\120\0\1\222\3\0\1\123\133\0"+
    "\10\33\7\0\2\33\1\316\27\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\317\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\22\33\1\320\7\33\4\0\30\33\27\0"+
    "\10\33\7\0\23\33\1\321\6\33\4\0\30\33\27\0"+
    "\10\33\7\0\1\33\1\322\30\33\4\0\30\33\27\0"+
    "\10\33\7\0\17\33\1\323\12\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\324\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\325\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\10\33\1\326\21\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\327\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\16\33\1\330\13\33\4\0\30\33\27\0"+
    "\10\33\7\0\23\33\1\331\6\33\4\0\30\33\27\0"+
    "\10\33\7\0\1\33\1\332\30\33\4\0\30\33\27\0"+
    "\10\33\7\0\15\33\1\333\14\33\4\0\30\33\27\0"+
    "\10\33\7\0\17\33\1\334\12\33\4\0\30\33\27\0"+
    "\10\33\7\0\22\33\1\335\7\33\4\0\30\33\27\0"+
    "\10\33\7\0\23\33\1\336\6\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\337\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\13\33\1\340\16\33\4\0\30\33\27\0"+
    "\10\33\7\0\23\33\1\341\6\33\4\0\30\33\27\0"+
    "\10\33\7\0\23\33\1\342\6\33\4\0\30\33\27\0"+
    "\10\33\7\0\13\33\1\343\7\33\1\344\6\33\4\0"+
    "\30\33\27\0\10\33\7\0\13\33\1\345\16\33\4\0"+
    "\30\33\27\0\10\33\7\0\32\33\4\0\22\33\1\346"+
    "\5\33\27\0\10\33\7\0\32\33\4\0\20\33\1\347"+
    "\7\33\27\0\10\33\7\0\32\33\4\0\24\33\1\350"+
    "\3\33\27\0\10\33\7\0\32\33\4\0\14\33\1\351"+
    "\13\33\27\0\10\33\7\0\32\33\4\0\7\33\1\352"+
    "\20\33\27\0\10\33\7\0\32\33\4\0\5\33\1\353"+
    "\22\33\27\0\10\33\7\0\32\33\4\0\2\33\1\354"+
    "\25\33\27\0\10\33\7\0\32\33\4\0\11\33\1\355"+
    "\16\33\27\0\10\33\7\0\32\33\4\0\5\33\1\356"+
    "\22\33\27\0\10\33\7\0\32\33\4\0\15\33\1\357"+
    "\12\33\27\0\10\33\7\0\32\33\4\0\3\33\1\360"+
    "\24\33\27\0\10\33\7\0\32\33\4\0\11\33\1\361"+
    "\16\33\27\0\10\33\7\0\32\33\4\0\13\33\1\362"+
    "\14\33\27\0\10\33\7\0\32\33\4\0\1\363\27\33"+
    "\27\0\10\33\7\0\32\33\4\0\22\33\1\364\5\33"+
    "\4\0\2\101\1\0\1\101\1\0\1\101\1\0\4\101"+
    "\1\365\1\366\60\101\1\0\1\101\1\367\3\101\1\370"+
    "\4\101\1\371\10\101\1\372\7\101\1\373\4\101\1\0"+
    "\1\101\1\0\1\101\1\0\17\101\1\374\6\101\1\276"+
    "\37\101\1\0\36\101\112\0\1\375\125\0\1\376\145\0"+
    "\1\377\137\0\1\u0100\133\0\1\u0101\34\0\10\u0102\7\0"+
    "\6\u0102\31\0\6\u0102\44\0\1\u0103\133\0\1\u0103\3\0"+
    "\10\310\120\0\1\u0103\3\0\5\310\1\u0104\2\305\120\0"+
    "\1\u0103\3\0\10\305\101\0\15\217\1\311\4\217\1\312"+
    "\111\217\17\0\1\u0105\133\0\1\u0105\3\0\1\u0106\7\313"+
    "\120\0\1\u0105\3\0\10\313\124\0\10\33\7\0\12\33"+
    "\1\u0107\17\33\4\0\30\33\27\0\10\33\7\0\10\33"+
    "\1\u0108\21\33\4\0\30\33\27\0\10\33\7\0\4\33"+
    "\1\u0109\25\33\4\0\30\33\27\0\10\33\7\0\13\33"+
    "\1\u010a\16\33\4\0\30\33\27\0\10\33\7\0\32\33"+
    "\4\0\1\u010b\27\33\27\0\10\33\7\0\15\33\1\u010c"+
    "\14\33\4\0\30\33\27\0\10\33\7\0\31\33\1\u010d"+
    "\4\0\30\33\27\0\10\33\7\0\10\33\1\u010e\21\33"+
    "\4\0\30\33\27\0\10\33\7\0\4\33\1\u010f\25\33"+
    "\4\0\30\33\27\0\10\33\7\0\32\33\4\0\1\u0110"+
    "\27\33\27\0\10\33\7\0\13\33\1\u0111\16\33\4\0"+
    "\30\33\27\0\10\33\7\0\32\33\4\0\1\u0112\27\33"+
    "\27\0\10\33\7\0\10\33\1\u0113\21\33\4\0\30\33"+
    "\27\0\10\33\7\0\2\33\1\u0114\27\33\4\0\30\33"+
    "\27\0\10\33\7\0\4\33\1\u0115\25\33\4\0\30\33"+
    "\27\0\10\33\7\0\10\33\1\u0116\21\33\4\0\30\33"+
    "\27\0\10\33\7\0\4\33\1\u0117\25\33\4\0\30\33"+
    "\27\0\10\33\7\0\4\33\1\u0118\25\33\4\0\30\33"+
    "\27\0\10\33\7\0\16\33\1\u0119\13\33\4\0\30\33"+
    "\27\0\10\33\7\0\32\33\4\0\5\33\1\u011a\22\33"+
    "\27\0\10\33\7\0\32\33\4\0\5\33\1\u011b\22\33"+
    "\27\0\10\33\7\0\32\33\4\0\5\33\1\u011c\22\33"+
    "\27\0\10\33\7\0\32\33\4\0\10\33\1\u011d\17\33"+
    "\27\0\10\33\7\0\32\33\4\0\13\33\1\u011e\14\33"+
    "\27\0\10\33\7\0\32\33\4\0\5\33\1\u011f\22\33"+
    "\27\0\10\33\7\0\32\33\4\0\16\33\1\u0120\11\33"+
    "\27\0\10\33\7\0\32\33\4\0\15\33\1\u0121\12\33"+
    "\27\0\10\33\7\0\32\33\4\0\22\33\1\u0122\5\33"+
    "\27\0\10\33\7\0\32\33\4\0\11\33\1\u0123\16\33"+
    "\27\0\10\33\7\0\32\33\4\0\15\33\1\u0124\12\33"+
    "\27\0\10\33\7\0\32\33\4\0\5\33\1\u0125\22\33"+
    "\27\0\10\33\7\0\32\33\4\0\11\33\1\u0126\16\33"+
    "\27\0\10\33\7\0\32\33\4\0\10\33\1\u0127\17\33"+
    "\4\0\2\101\1\0\1\101\1\0\1\101\1\0\4\101"+
    "\1\365\61\101\1\0\1\u0128\37\101\1\0\1\101\1\0"+
    "\1\101\1\0\5\101\1\366\60\101\1\0\1\u0129\37\101"+
    "\1\0\1\101\1\0\1\101\1\0\66\101\1\0\1\101"+
    "\1\u012a\36\101\1\0\1\101\1\0\1\101\1\0\66\101"+
    "\1\0\3\101\1\u012b\34\101\1\0\1\101\1\0\1\101"+
    "\1\0\66\101\1\0\7\101\1\u012c\30\101\1\0\1\101"+
    "\1\0\1\101\1\0\66\101\1\0\3\101\1\u012d\3\101"+
    "\1\u012e\6\101\1\u012f\5\101\1\u0130\13\101\1\0\1\101"+
    "\1\0\1\101\1\0\66\101\1\0\1\u0131\32\101\1\373"+
    "\4\101\1\0\1\101\1\0\1\101\1\0\17\101\1\374"+
    "\46\101\1\0\1\u0132\35\101\107\0\1\u0133\131\0\1\u0134"+
    "\146\0\1\u0135\121\0\1\u0136\146\0\1\u0137\35\0\10\u0138"+
    "\7\0\6\u0138\31\0\6\u0138\50\0\1\u0139\1\u013a\1\u013b"+
    "\5\u013c\120\0\1\u0103\3\0\6\305\126\0\1\u013d\1\u013e"+
    "\6\u013f\120\0\1\u0105\3\0\1\313\133\0\10\33\7\0"+
    "\25\33\1\u0140\4\33\4\0\30\33\27\0\10\33\7\0"+
    "\3\33\1\u0141\26\33\4\0\30\33\27\0\10\33\7\0"+
    "\4\33\1\u0142\25\33\4\0\30\33\27\0\10\33\7\0"+
    "\20\33\1\u0143\11\33\4\0\30\33\27\0\10\33\7\0"+
    "\16\33\1\u0144\13\33\4\0\30\33\27\0\10\33\7\0"+
    "\17\33\1\u0145\12\33\4\0\30\33\27\0\10\33\7\0"+
    "\21\33\1\u0146\10\33\4\0\30\33\27\0\10\33\7\0"+
    "\20\33\1\u0147\11\33\4\0\30\33\27\0\10\33\7\0"+
    "\4\33\1\u0148\25\33\4\0\30\33\27\0\10\33\7\0"+
    "\22\33\1\u0149\7\33\4\0\30\33\27\0\10\33\7\0"+
    "\16\33\1\u014a\13\33\4\0\30\33\27\0\10\33\7\0"+
    "\23\33\1\u014b\6\33\4\0\30\33\27\0\10\33\7\0"+
    "\2\33\1\u014c\27\33\4\0\30\33\27\0\10\33\7\0"+
    "\26\33\1\u014d\3\33\4\0\30\33\27\0\10\33\7\0"+
    "\32\33\4\0\15\33\1\u014e\12\33\27\0\10\33\7\0"+
    "\32\33\4\0\3\33\1\u014f\24\33\27\0\10\33\7\0"+
    "\32\33\4\0\15\33\1\u0150\12\33\27\0\10\33\7\0"+
    "\32\33\4\0\22\33\1\u0151\5\33\27\0\10\33\7\0"+
    "\32\33\4\0\20\33\1\u0152\7\33\27\0\10\33\7\0"+
    "\32\33\4\0\15\33\1\u0153\12\33\27\0\10\33\7\0"+
    "\32\33\4\0\22\33\1\u0154\5\33\27\0\10\33\7\0"+
    "\27\33\1\u0155\1\u0156\1\33\4\0\30\33\27\0\10\33"+
    "\7\0\32\33\4\0\1\33\1\u0157\26\33\27\0\10\33"+
    "\7\0\32\33\4\0\7\33\1\u0158\20\33\27\0\10\33"+
    "\7\0\32\33\4\0\21\33\1\u0159\6\33\27\0\10\33"+
    "\7\0\32\33\4\0\21\33\1\u015a\6\33\4\0\2\101"+
    "\1\0\1\101\1\0\1\101\1\0\24\101\1\u015b\41\101"+
    "\1\0\40\101\1\0\1\101\1\0\1\101\1\0\66\101"+
    "\1\0\24\101\1\u012a\13\101\1\0\1\101\1\0\1\101"+
    "\1\0\66\101\1\0\3\101\1\u015c\34\101\1\0\1\101"+
    "\1\0\1\101\1\0\66\101\1\0\6\101\1\u015d\31\101"+
    "\1\0\1\101\1\0\1\101\1\0\66\101\1\0\22\101"+
    "\1\u015e\15\101\1\0\1\101\1\0\1\101\1\0\66\101"+
    "\1\0\13\101\1\u015f\24\101\1\0\1\101\1\0\1\101"+
    "\1\0\66\101\1\0\3\101\1\u0160\32\101\120\0\1\u0161"+
    "\133\0\1\u0162\21\0\1\u0163\226\0\1\u0164\143\0\1\u0165"+
    "\45\0\10\u0166\7\0\6\u0166\31\0\6\u0166\41\0\1\u0167"+
    "\133\0\1\u0167\6\0\10\u013c\115\0\1\u0167\6\0\5\u013c"+
    "\1\u0168\2\u0139\115\0\1\u0167\6\0\10\u0139\140\0\1\u0169"+
    "\117\0\1\u016a\7\u013d\4\0\1\u0169\117\0\10\u013d\4\0"+
    "\1\u0169\117\0\10\33\7\0\4\33\1\u016b\25\33\4\0"+
    "\30\33\27\0\10\33\7\0\24\33\1\u016c\5\33\4\0"+
    "\30\33\27\0\10\33\7\0\15\33\1\u016d\14\33\4\0"+
    "\30\33\27\0\10\33\7\0\13\33\1\u016e\16\33\4\0"+
    "\30\33\27\0\10\33\7\0\24\33\1\u016f\5\33\4\0"+
    "\30\33\27\0\10\33\7\0\4\33\1\u0170\25\33\4\0"+
    "\30\33\27\0\10\33\7\0\15\33\1\u0171\14\33\4\0"+
    "\30\33\27\0\10\33\7\0\32\33\4\0\1\u0172\27\33"+
    "\27\0\10\33\7\0\1\u0173\31\33\4\0\30\33\27\0"+
    "\10\33\7\0\32\33\4\0\22\33\1\u0174\5\33\27\0"+
    "\10\33\7\0\32\33\4\0\22\33\1\u0175\5\33\27\0"+
    "\10\33\7\0\32\33\4\0\22\33\1\u0176\5\33\27\0"+
    "\10\33\7\0\32\33\4\0\21\33\1\u0177\6\33\27\0"+
    "\10\33\7\0\32\33\4\0\1\33\1\u0178\26\33\27\0"+
    "\10\33\7\0\32\33\4\0\13\33\1\u0179\14\33\27\0"+
    "\10\33\7\0\32\33\4\0\1\u017a\27\33\4\0\2\101"+
    "\1\0\1\101\1\0\1\101\1\0\66\101\1\0\1\u017b"+
    "\37\101\1\0\1\101\1\0\1\101\1\0\66\101\1\0"+
    "\22\101\1\u017c\15\101\1\0\1\101\1\0\1\101\1\0"+
    "\24\101\1\u017d\41\101\1\0\40\101\1\0\1\101\1\0"+
    "\1\101\1\0\66\101\1\0\13\101\1\u017e\24\101\1\0"+
    "\1\101\1\0\1\101\1\0\66\101\1\0\15\101\1\u017f"+
    "\22\101\1\0\1\101\1\0\1\101\1\0\66\101\1\0"+
    "\22\101\1\u0180\13\101\116\0\1\u0181\23\0\1\u0182\241\0"+
    "\1\u0183\146\0\1\u0184\20\0\1\u0167\6\0\6\u0139\126\0"+
    "\1\u013d\13\0\1\u0169\117\0\10\33\7\0\4\33\1\u0185"+
    "\25\33\4\0\30\33\27\0\10\33\7\0\23\33\1\u0186"+
    "\6\33\4\0\30\33\27\0\10\33\7\0\4\33\1\u0187"+
    "\25\33\4\0\30\33\27\0\10\33\7\0\4\33\1\u0188"+
    "\25\33\4\0\30\33\27\0\10\33\7\0\21\33\1\u0189"+
    "\10\33\4\0\30\33\27\0\10\33\7\0\20\33\1\u018a"+
    "\11\33\4\0\30\33\27\0\10\33\7\0\13\33\1\u018b"+
    "\16\33\4\0\30\33\27\0\10\33\7\0\32\33\4\0"+
    "\21\33\1\u018c\6\33\27\0\10\33\7\0\32\33\4\0"+
    "\22\33\1\u018d\5\33\27\0\10\33\7\0\32\33\4\0"+
    "\22\33\1\u018e\5\33\4\0\2\101\1\0\1\101\1\0"+
    "\1\101\1\0\66\101\1\0\24\101\1\u018f\13\101\1\0"+
    "\1\101\1\0\1\101\1\0\66\101\1\0\1\u0128\37\101"+
    "\1\0\1\101\1\0\1\101\1\0\66\101\1\0\20\101"+
    "\1\u0190\17\101\1\0\1\101\1\0\1\101\1\0\66\101"+
    "\1\0\7\101\1\u0191\30\101\1\0\1\101\1\0\1\101"+
    "\1\0\11\101\1\u0192\12\101\1\u0193\41\101\1\0\36\101"+
    "\123\0\1\u0194\121\0\1\u0195\127\0\1\u0196\51\0\10\33"+
    "\7\0\22\33\1\u0197\7\33\4\0\30\33\27\0\10\33"+
    "\7\0\1\u0198\31\33\4\0\30\33\27\0\10\33\7\0"+
    "\32\33\4\0\1\u0199\27\33\27\0\10\33\7\0\22\33"+
    "\1\u019a\7\33\4\0\30\33\27\0\10\33\7\0\10\33"+
    "\1\u019b\21\33\4\0\30\33\27\0\10\33\7\0\24\33"+
    "\1\u019c\5\33\4\0\30\33\27\0\10\33\7\0\32\33"+
    "\4\0\11\33\1\u019d\16\33\27\0\10\33\7\0\32\33"+
    "\4\0\10\33\1\u019e\17\33\4\0\2\101\1\0\1\101"+
    "\1\0\1\101\1\0\24\101\1\u019f\41\101\1\0\40\101"+
    "\1\0\1\101\1\0\1\101\1\0\66\101\1\0\25\101"+
    "\1\u01a0\12\101\1\0\1\101\1\0\1\101\1\0\24\101"+
    "\1\u01a1\41\101\1\0\40\101\1\0\1\101\1\0\1\101"+
    "\1\0\14\101\10\u01a2\42\101\1\0\40\101\1\0\1\101"+
    "\1\0\1\101\1\0\14\101\10\u01a2\42\101\1\0\1\u01a3"+
    "\35\101\115\0\1\u01a4\131\0\1\u01a5\26\0\1\u01a6\150\0"+
    "\10\33\7\0\23\33\1\u01a7\6\33\4\0\30\33\27\0"+
    "\10\33\7\0\13\33\1\u01a8\16\33\4\0\30\33\27\0"+
    "\10\33\7\0\20\33\1\u01a9\11\33\4\0\30\33\27\0"+
    "\10\33\7\0\23\33\1\u01aa\6\33\4\0\30\33\27\0"+
    "\10\33\7\0\5\33\1\u01ab\24\33\4\0\30\33\27\0"+
    "\10\33\7\0\4\33\1\u01ac\25\33\4\0\30\33\27\0"+
    "\10\33\7\0\32\33\4\0\16\33\1\u01ad\11\33\27\0"+
    "\10\33\7\0\32\33\4\0\1\33\1\u01ae\26\33\4\0"+
    "\2\101\1\0\1\101\1\0\1\101\1\0\66\101\1\0"+
    "\1\u0132\37\101\1\0\1\101\1\0\1\101\1\0\66\101"+
    "\1\0\23\101\1\u01af\14\101\1\0\1\101\1\0\1\101"+
    "\1\0\66\101\1\0\1\u0129\37\101\1\0\1\101\1\0"+
    "\1\101\1\0\14\101\10\u01a2\1\u01b0\41\101\1\0\36\101"+
    "\104\0\1\u01b1\155\0\1\u01b2\30\0\10\33\7\0\10\33"+
    "\1\u01b3\21\33\4\0\30\33\27\0\10\33\7\0\24\33"+
    "\1\u01b4\5\33\4\0\30\33\27\0\10\33\7\0\10\33"+
    "\1\u01b5\21\33\4\0\30\33\27\0\10\33\7\0\22\33"+
    "\1\u01b6\7\33\4\0\30\33\27\0\10\33\7\0\32\33"+
    "\4\0\15\33\1\u01b7\12\33\27\0\10\33\7\0\32\33"+
    "\4\0\22\33\1\u01b8\5\33\4\0\2\101\1\0\1\101"+
    "\1\0\1\101\1\0\24\101\1\u01b9\41\101\1\0\40\101"+
    "\1\0\1\101\1\0\1\101\1\0\66\101\1\0\1\u01ba"+
    "\35\101\103\0\1\u01bb\36\0\1\u01bc\150\0\10\33\7\0"+
    "\16\33\1\u01bd\13\33\4\0\30\33\27\0\10\33\7\0"+
    "\4\33\1\u01be\25\33\4\0\30\33\27\0\10\33\7\0"+
    "\16\33\1\u01bf\13\33\4\0\30\33\27\0\10\33\7\0"+
    "\23\33\1\u01c0\6\33\4\0\30\33\27\0\10\33\7\0"+
    "\32\33\4\0\1\u01c1\27\33\4\0\2\101\1\0\1\101"+
    "\1\0\1\101\1\0\66\101\1\0\1\u0131\35\101\116\0"+
    "\1\u01c2\40\0\10\33\7\0\15\33\1\u01c3\14\33\4\0"+
    "\30\33\27\0\10\33\7\0\22\33\1\u01c4\7\33\4\0"+
    "\30\33\27\0\10\33\7\0\15\33\1\u01c5\14\33\4\0"+
    "\30\33\27\0\10\33\7\0\10\33\1\u01c6\21\33\4\0"+
    "\30\33\27\0\10\33\7\0\32\33\4\0\17\33\1\u01c7"+
    "\10\33\117\0\1\u01c8\43\0\10\33\7\0\23\33\1\u01c9"+
    "\6\33\4\0\30\33\27\0\10\33\7\0\16\33\1\u01ca"+
    "\13\33\4\0\30\33\27\0\10\33\7\0\32\33\4\0"+
    "\16\33\1\u01cb\11\33\122\0\1\u01cc\40\0\10\33\7\0"+
    "\10\33\1\u01cd\21\33\4\0\30\33\27\0\10\33\7\0"+
    "\15\33\1\u01ce\14\33\4\0\30\33\27\0\10\33\7\0"+
    "\32\33\4\0\12\33\1\u01cf\15\33\124\0\1\u01d0\36\0"+
    "\10\33\7\0\16\33\1\u01d1\13\33\4\0\30\33\27\0"+
    "\10\33\7\0\32\33\4\0\5\33\1\u01d2\22\33\12\0"+
    "\1\u01d3\150\0\10\33\7\0\15\33\1\u01d4\14\33\4\0"+
    "\30\33\27\0\10\33\7\0\32\33\4\0\14\33\1\u01d5"+
    "\13\33\27\0\10\33\7\0\32\33\4\0\16\33\1\u01d6"+
    "\11\33\27\0\10\33\7\0\32\33\4\0\15\33\1\u01d7"+
    "\12\33\4\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[35052];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\2\11\5\1\1\11\2\1\5\11\3\1\2\11"+
    "\3\1\1\11\24\1\3\11\13\1\1\11\1\1\2\11"+
    "\1\1\1\11\2\1\1\11\5\0\1\11\13\0\3\11"+
    "\46\1\1\11\1\1\4\11\10\0\1\11\2\0\1\1"+
    "\2\0\53\1\13\0\1\11\3\0\57\1\12\0\54\1"+
    "\15\0\41\1\2\0\1\11\2\0\2\11\1\0\1\11"+
    "\1\0\26\1\1\0\1\11\2\0\17\1\3\0\15\1"+
    "\2\0\1\11\12\1\2\0\10\1\1\0\1\11\5\1"+
    "\1\0\5\1\1\0\3\1\1\0\3\1\1\0\2\1"+
    "\1\11\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[471];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  private boolean zzEOFDone;

  /* user code: */
    /****************** codigo de usuario ***********************/

        StringBuffer string;
        ArrayList<Integer> RGBvalues = new ArrayList<>();
        ArrayList<Float> HSLvalues = new ArrayList<>();

        /* Codigo para devolver valores utiles al parser */

        private ArrayList<Integer> extractRBGvalues(String rgbText){
            RGBvalues.clear();
            String[] values = rgbText.substring(1, rgbText.length() - 1).split(",");
            for (String value : values) {
                RGBvalues.add(Integer.parseInt(value.trim()));
            }
            return new ArrayList<>(RGBvalues);
        }

        private ArrayList<Float> extractHSLvalues(String hslText){
            HSLvalues.clear();
            String[] values = hslText.substring(1, hslText.length() - 1).split(",");
            for (int i = 0; i < values.length; i++) {
                float val  = Float.parseFloat(values[i].trim());
                if (i == 0) {
                    HSLvalues.add(val % 360);
                } else {
                    float porcentaje = Math.max(0, Math.min(100, val)) / 100f;
                    HSLvalues.add(porcentaje);
                }
            }
            return new ArrayList<>(HSLvalues) ;
        }

        private String extractStars(String starText){
           String cleaned = starText.replaceAll("[^0-9]", "");
           Integer number =  Integer.parseInt(cleaned);
           String result = "";
           for (int i = 0; i < number; i++) {
                result += "\u2B50";
           }
            return result;
        }

        /* Codigo para el manejo de errores */

        private List<ErrorReport> errorList;

        public List<ErrorReport> getLexicalErrors(){
            return this.errorList;
        }

        /*-----------------------------------------------
              Codigo para el parser
        -------------------------------------------------*/
        private Symbol symbol(int type){
            return new Symbol(type, yyline+1, yycolumn+1);
        }

        private Symbol symbol(int type, Object valor){
            return new Symbol(type, yyline+1, yycolumn+1, valor);
        }

        private void error(String message){
            /* Lexema | linea | columna | tipo | desc */
             errorList.add(new ErrorReport(message, yyline+1, yycolumn+1, "Lexico", "Simbolo no reconocido"));
        }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Lexer(java.io.Reader in) {
      /****************** dentro del constructor ******************/
    errorList = new ArrayList<>();
    string = new StringBuffer();

    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
  yyclose();    }
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  @Override  public java_cup.runtime.Symbol next_token() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
              {
                return symbol(sym.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { error(yytext());
            }
          // fall through
          case 103: break;
          case 2:
            { /* ignorar */
            }
          // fall through
          case 104: break;
          case 3:
            { string.setLength(0); yybegin(STRING);
            }
          // fall through
          case 105: break;
          case 4:
            { 
            }
          // fall through
          case 106: break;
          case 5:
            { return symbol(sym.MOD);
            }
          // fall through
          case 107: break;
          case 6:
            { return symbol(sym.LPAREN);
            }
          // fall through
          case 108: break;
          case 7:
            { return symbol(sym.RPAREN);
            }
          // fall through
          case 109: break;
          case 8:
            { return symbol(sym.TIMES);
            }
          // fall through
          case 110: break;
          case 9:
            { return symbol(sym.PLUS);
            }
          // fall through
          case 111: break;
          case 10:
            { return symbol(sym.COMMA);
            }
          // fall through
          case 112: break;
          case 11:
            { return symbol(sym.MINUS);
            }
          // fall through
          case 113: break;
          case 12:
            { return symbol(sym.DOT);
            }
          // fall through
          case 114: break;
          case 13:
            { return symbol(sym.DIVIDE);
            }
          // fall through
          case 115: break;
          case 14:
            { String numText = yytext();
                        if (numText.contains(".")) {
                            return symbol(sym.NUMBER, Double.parseDouble(numText));
                         } else {
                            return symbol(sym.NUMBER, Integer.parseInt(numText));
                         }
            }
          // fall through
          case 116: break;
          case 15:
            { return symbol(sym.COLON);
            }
          // fall through
          case 117: break;
          case 16:
            { return symbol(sym.SEMICOLON);
            }
          // fall through
          case 118: break;
          case 17:
            { return symbol(sym.LT);
            }
          // fall through
          case 119: break;
          case 18:
            { return symbol(sym.ASSIGN);
            }
          // fall through
          case 120: break;
          case 19:
            { return symbol(sym.GT);
            }
          // fall through
          case 121: break;
          case 20:
            { return symbol(sym.COMODIN);
            }
          // fall through
          case 122: break;
          case 21:
            { return symbol(sym.ID, yytext());
            }
          // fall through
          case 123: break;
          case 22:
            { return symbol(sym.LBRACKET);
            }
          // fall through
          case 124: break;
          case 23:
            { return symbol(sym.RBRACKET);
            }
          // fall through
          case 125: break;
          case 24:
            { return symbol(sym.POWER);
            }
          // fall through
          case 126: break;
          case 25:
            { return symbol(sym.LBRACE);
            }
          // fall through
          case 127: break;
          case 26:
            { return symbol(sym.RBRACE);
            }
          // fall through
          case 128: break;
          case 27:
            { return symbol(sym.NOT);
            }
          // fall through
          case 129: break;
          case 28:
            { string.append( yytext() );
            }
          // fall through
          case 130: break;
          case 29:
            { yybegin(YYINITIAL);
                            return symbol(sym.STRCHAIN, string.toString());
            }
          // fall through
          case 131: break;
          case 30:
            { string.append('\\');
            }
          // fall through
          case 132: break;
          case 31:
            { return symbol(sym.NEQ);
            }
          // fall through
          case 133: break;
          case 32:
            { return symbol(sym.AND);
            }
          // fall through
          case 134: break;
          case 33:
            { return symbol(sym.LTE);
            }
          // fall through
          case 135: break;
          case 34:
            { return symbol(sym.EQ);
            }
          // fall through
          case 136: break;
          case 35:
            { return symbol(sym.GTE);
            }
          // fall through
          case 137: break;
          case 36:
            { return symbol(sym.DO);
            }
          // fall through
          case 138: break;
          case 37:
            { return symbol(sym.IF);
            }
          // fall through
          case 139: break;
          case 38:
            { return symbol(sym.IN);
            }
          // fall through
          case 140: break;
          case 39:
            { return symbol(sym.OR);
            }
          // fall through
          case 141: break;
          case 40:
            { string.append('\"');
            }
          // fall through
          case 142: break;
          case 41:
            { string.append('\n');
            }
          // fall through
          case 143: break;
          case 42:
            { string.append('\r');
            }
          // fall through
          case 144: break;
          case 43:
            { string.append('\t');
            }
          // fall through
          case 145: break;
          case 44:
            { return symbol(sym.RANGE);
            }
          // fall through
          case 146: break;
          case 45:
            { return symbol(sym.FOR);
            }
          // fall through
          case 147: break;
          case 46:
            { return symbol(sym.RED);
            }
          // fall through
          case 148: break;
          case 47:
            { return symbol(sym.SKY);
            }
          // fall through
          case 149: break;
          case 48:
            { return symbol(sym.BLUE);
            }
          // fall through
          case 150: break;
          case 49:
            { return symbol(sym.ELSE);
            }
          // fall through
          case 151: break;
          case 50:
            { return symbol(sym.LINE);
            }
          // fall through
          case 152: break;
          case 51:
            { return symbol(sym.MONO);
            }
          // fall through
          case 153: break;
          case 52:
            { return symbol(sym.TEXT);
            }
          // fall through
          case 154: break;
          case 53:
            { return symbol(sym.DRAW);
            }
          // fall through
          case 155: break;
          case 54:
            { return symbol(sym.BLACK);
            }
          // fall through
          case 156: break;
          case 55:
            { return symbol(sym.GREEN);
            }
          // fall through
          case 157: break;
          case 56:
            { return symbol(sym.TABLE);
            }
          // fall through
          case 158: break;
          case 57:
            { return symbol(sym.WHILE);
            }
          // fall through
          case 159: break;
          case 58:
            { return symbol(sym.WHITE);
            }
          // fall through
          case 160: break;
          case 59:
            { return symbol(sym.LABEL);
            }
          // fall through
          case 161: break;
          case 60:
            { return symbol(sym.WIDTH);
            }
          // fall through
          case 162: break;
          case 61:
            { string.append( "\uD83D\uDE22");
            }
          // fall through
          case 163: break;
          case 62:
            { string.append( "\uD83D\uDE00" );
            }
          // fall through
          case 164: break;
          case 63:
            { string.append( "\uD83D\uDE10");
            }
          // fall through
          case 165: break;
          case 64:
            { string.append( "\u2764\uFE0F" );
            }
          // fall through
          case 166: break;
          case 65:
            { return symbol(sym.DOTTED);
            }
          // fall through
          case 167: break;
          case 66:
            { return symbol(sym.DOUBLE);
            }
          // fall through
          case 168: break;
          case 67:
            { return symbol(sym.APINUMBER);
            }
          // fall through
          case 169: break;
          case 68:
            { return symbol(sym.PURPLE);
            }
          // fall through
          case 170: break;
          case 69:
            { return symbol(sym.YELLOW);
            }
          // fall through
          case 171: break;
          case 70:
            { return symbol(sym.HEIGHT);
            }
          // fall through
          case 172: break;
          case 71:
            { return symbol(sym.TYPENUMBER);
            }
          // fall through
          case 173: break;
          case 72:
            { return symbol(sym.POINTX);
            }
          // fall through
          case 174: break;
          case 73:
            { return symbol(sym.POINTY);
            }
          // fall through
          case 175: break;
          case 74:
            { return symbol(sym.TYPESTRING);
            }
          // fall through
          case 176: break;
          case 75:
            { return symbol(sym.STYLES);
            }
          // fall through
          case 177: break;
          case 76:
            { return symbol(sym.PARAMCOLOR);
            }
          // fall through
          case 178: break;
          case 77:
            { return symbol(sym.HEX_COLOR, yytext());
            }
          // fall through
          case 179: break;
          case 78:
            { return symbol(sym.RGB_COLOR, extractRBGvalues(yytext()));
            }
          // fall through
          case 180: break;
          case 79:
            { return symbol(sym.HSL_COLOR, extractHSLvalues(yytext()));
            }
          // fall through
          case 181: break;
          case 80:
            { return symbol(sym.CURSIVE);
            }
          // fall through
          case 182: break;
          case 81:
            { return symbol(sym.SECTION);
            }
          // fall through
          case 183: break;
          case 82:
            { return symbol(sym.CONTENT);
            }
          // fall through
          case 184: break;
          case 83:
            { return symbol(sym.CORRECT);
            }
          // fall through
          case 185: break;
          case 84:
            { return symbol(sym.OPTIONS);
            }
          // fall through
          case 186: break;
          case 85:
            { return symbol(sym.TYPESPECIAL);
            }
          // fall through
          case 187: break;
          case 86:
            { string.append( "\uD83D\uDC31" );
            }
          // fall through
          case 188: break;
          case 87:
            { return symbol(sym.PARAMBORDER);
            }
          // fall through
          case 189: break;
          case 88:
            { return symbol(sym.VERTICAL);
            }
          // fall through
          case 190: break;
          case 89:
            { return symbol(sym.ELEMENTS);
            }
          // fall through
          case 191: break;
          case 90:
            { string.append( "\u2B50" );
            }
          // fall through
          case 192: break;
          case 91:
            { return symbol(sym.PARAMSIZE);
            }
          // fall through
          case 193: break;
          case 92:
            { return symbol(sym.HORIZONTAL);
            }
          // fall through
          case 194: break;
          case 93:
            { return symbol(sym.SANS_SERIF);
            }
          // fall through
          case 195: break;
          case 94:
            { return symbol(sym.ORIENTATION);
            }
          // fall through
          case 196: break;
          case 95:
            { string.append( extractStars(yytext()) );
            }
          // fall through
          case 197: break;
          case 96:
            { return symbol(sym.PARAMFONT);
            }
          // fall through
          case 198: break;
          case 97:
            { return symbol(sym.DROP_QUESTION);
            }
          // fall through
          case 199: break;
          case 98:
            { return symbol(sym.OPEN_QUESTION);
            }
          // fall through
          case 200: break;
          case 99:
            { return symbol(sym.SELECT_QUESTION);
            }
          // fall through
          case 201: break;
          case 100:
            { return symbol(sym.PARAMBACKGROUND);
            }
          // fall through
          case 202: break;
          case 101:
            { return symbol(sym.MULTIPLE_QUESTION);
            }
          // fall through
          case 203: break;
          case 102:
            { return symbol(sym.POKEAPI);
            }
          // fall through
          case 204: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
