
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.joseruiz.formMaker.compiler;

/** CUP generated interface containing symbol constants. */
public interface sym {
  /* terminals */
  public static final int HORIZONTAL = 42;
  public static final int SELECT_QUESTION = 50;
  public static final int TIMES = 4;
  public static final int GT = 10;
  public static final int PARAMFONT = 74;
  public static final int TABLE = 45;
  public static final int TYPESPECIAL = 21;
  public static final int SANS_SERIF = 79;
  public static final int DROP_QUESTION = 48;
  public static final int TYPESTRING = 20;
  public static final int BLUE = 61;
  public static final int YELLOW = 65;
  public static final int COMMA = 29;
  public static final int ELEMENTS = 43;
  public static final int RBRACE = 24;
  public static final int DRAW = 52;
  public static final int WHITE = 67;
  public static final int RPAREN = 9;
  public static final int OPEN_QUESTION = 47;
  public static final int LT = 11;
  public static final int BLACK = 66;
  public static final int APINUMBER = 86;
  public static final int DOUBLE = 82;
  public static final int LBRACE = 23;
  public static final int LPAREN = 8;
  public static final int PARAMCOLOR = 72;
  public static final int POKEAPI = 85;
  public static final int NOT = 18;
  public static final int TEXT = 46;
  public static final int PURPLE = 63;
  public static final int WIDTH = 33;
  public static final int EQ = 14;
  public static final int RGB_COLOR = 69;
  public static final int STYLES = 44;
  public static final int MOD = 7;
  public static final int NUMBER = 71;
  public static final int CURSIVE = 78;
  public static final int MONO = 77;
  public static final int STRCHAIN = 84;
  public static final int PLUS = 2;
  public static final int DIVIDE = 5;
  public static final int WHILE = 55;
  public static final int ASSIGN = 22;
  public static final int PARAMBACKGROUND = 73;
  public static final int HSL_COLOR = 70;
  public static final int DO = 56;
  public static final int FOR = 57;
  public static final int COMODIN = 31;
  public static final int ORIENTATION = 40;
  public static final int ELSE = 54;
  public static final int MULTIPLE_QUESTION = 51;
  public static final int DOT = 30;
  public static final int LTE = 13;
  public static final int CORRECT = 49;
  public static final int POWER = 6;
  public static final int CONTENT = 37;
  public static final int EOF = 0;
  public static final int SEMICOLON = 28;
  public static final int VERTICAL = 41;
  public static final int LINE = 80;
  public static final int TYPENUMBER = 19;
  public static final int LABEL = 35;
  public static final int MINUS = 3;
  public static final int PARAMSIZE = 75;
  public static final int IN = 58;
  public static final int OR = 17;
  public static final int SKY = 64;
  public static final int error = 1;
  public static final int GTE = 12;
  public static final int IF = 53;
  public static final int ID = 83;
  public static final int DOTTED = 81;
  public static final int PARAMBORDER = 76;
  public static final int HEX_COLOR = 68;
  public static final int COLON = 27;
  public static final int HEIGHT = 34;
  public static final int RBRACKET = 26;
  public static final int RED = 60;
  public static final int RANGE = 59;
  public static final int POINTY = 39;
  public static final int OPTIONS = 36;
  public static final int NEQ = 15;
  public static final int POINTX = 38;
  public static final int AND = 16;
  public static final int LBRACKET = 25;
  public static final int SECTION = 32;
  public static final int GREEN = 62;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PLUS",
  "MINUS",
  "TIMES",
  "DIVIDE",
  "POWER",
  "MOD",
  "LPAREN",
  "RPAREN",
  "GT",
  "LT",
  "GTE",
  "LTE",
  "EQ",
  "NEQ",
  "AND",
  "OR",
  "NOT",
  "TYPENUMBER",
  "TYPESTRING",
  "TYPESPECIAL",
  "ASSIGN",
  "LBRACE",
  "RBRACE",
  "LBRACKET",
  "RBRACKET",
  "COLON",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "COMODIN",
  "SECTION",
  "WIDTH",
  "HEIGHT",
  "LABEL",
  "OPTIONS",
  "CONTENT",
  "POINTX",
  "POINTY",
  "ORIENTATION",
  "VERTICAL",
  "HORIZONTAL",
  "ELEMENTS",
  "STYLES",
  "TABLE",
  "TEXT",
  "OPEN_QUESTION",
  "DROP_QUESTION",
  "CORRECT",
  "SELECT_QUESTION",
  "MULTIPLE_QUESTION",
  "DRAW",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "IN",
  "RANGE",
  "RED",
  "BLUE",
  "GREEN",
  "PURPLE",
  "SKY",
  "YELLOW",
  "BLACK",
  "WHITE",
  "HEX_COLOR",
  "RGB_COLOR",
  "HSL_COLOR",
  "NUMBER",
  "PARAMCOLOR",
  "PARAMBACKGROUND",
  "PARAMFONT",
  "PARAMSIZE",
  "PARAMBORDER",
  "MONO",
  "CURSIVE",
  "SANS_SERIF",
  "LINE",
  "DOTTED",
  "DOUBLE",
  "ID",
  "STRCHAIN",
  "POKEAPI",
  "APINUMBER"
  };
}

